import { DIMENSIONS } from '../dimensions/dimensions';
import {
  COMPONENT_NAMES,
  COMPONENT_TYPES,
  ELEVATION_NAMES,
  SUPPLIER_SLUGS,
} from '../names/names';

const customCubes = [
  {
    name: COMPONENT_NAMES.AIR_CONDITIONER,
    position: {
      x: 105,
      y: 40,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/front-view/ac.svg`,
    sideImg: `${COMPONENT_TYPES.ELECTRICAL}/side-view/ac.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/ac.svg`,
    desc: 'P203-1-101',
    objWidth: 16,
    objHeight: 23,
    objThickness: 8,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 1075,
    priceSurface: 1075,
    model: 'airconditioner',
    fixed: true,
    fixedSide: ELEVATION_NAMES.BACK,
    alwaysShowOn: [
      ELEVATION_NAMES.BACK,
      ELEVATION_NAMES.LEFT,
      ELEVATION_NAMES.RIGHT,
    ],
  },
  {
    name: COMPONENT_NAMES.ELECTRICAL_PANEL_60_AMP,
    position: {
      x: 7,
      y: 90,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/front-view/box-panel.svg`,
    sideImg: `${COMPONENT_TYPES.ELECTRICAL}/side-view/box-panel.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/box-panel.svg`,
    desc: 'P611-1-101',
    objWidth: 10,
    objHeight: 17,
    objThickness: 5,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 975,
    priceSurface: 1075,
    model: 'electricalpanel',
    fixed: true,
    fixedSide: ELEVATION_NAMES.BACK,
    alwaysShowOn: [
      ELEVATION_NAMES.BACK,
      ELEVATION_NAMES.LEFT,
      ELEVATION_NAMES.RIGHT,
    ],
  },
  {
    name: COMPONENT_NAMES.ELECTRICAL_PANEL_100_AMP,
    position: {
      x: 7,
      y: 90,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/front-view/box-panel.svg`,
    sideImg: `${COMPONENT_TYPES.ELECTRICAL}/side-view/box-panel.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/box-panel.svg`,
    desc: 'P611-1-102',
    objWidth: 10,
    objHeight: 17,
    objThickness: 5,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 975,
    priceSurface: 1075,
    model: 'electricalpanel',
    fixed: true,
    fixedSide: ELEVATION_NAMES.BACK,
    alwaysShowOn: [
      ELEVATION_NAMES.BACK,
      ELEVATION_NAMES.LEFT,
      ELEVATION_NAMES.RIGHT,
    ],
  },
  {
    name: COMPONENT_NAMES.BASEBOARD_HEATER,
    position: {
      x: 15,
      y: 5,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/baseboard-heater.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/baseboard-heater.svg`,
    desc: 'P655-1-01',
    objWidth: 50,
    objHeight: 3,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 450,
    priceSurface: 450,
    model: 'heater',
    fixed: false,
    rotate: 0,
  },
  {
    name: COMPONENT_NAMES.OUTLET,
    position: {
      x: 30,
      y: 30,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/outlet.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/outlet.svg`,
    desc: 'P604-1-1501',
    objWidth: 4,
    objHeight: 8,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 325,
    priceSurface: 395,
    model: 'outlet',
    fixed: false,
    rotate: 0,
  },
  {
    name: COMPONENT_NAMES.EXHAUST_FAN,
    position: {
      x: 0,
      y: 42,
    },
    frontImg: `${COMPONENT_TYPES.ELECTRICAL}/front-view/exhaust-fan.svg`,
    floorPlanImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/exhaust-fan.svg`,
    desc: 'P203-1-307',
    objWidth: 17,
    objHeight: 19,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceSurface: 1735,
    priceRecessed: 1735,
    model: 'fan',
    fixed: true,
    fixedSide: ELEVATION_NAMES.RIGHT,
    alwaysShowOn: [ELEVATION_NAMES.RIGHT],
  },
  {
    name: COMPONENT_NAMES.WRAP_LIGHT,
    position: {
      x: 18,
      y: 0,
    },
    floorPlanImg: {
      TEN: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/10/wrap-light-dash.svg`,
      TWENTY: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/20/wrap-light-dash.svg`,
      FORTY: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/40/wrap-light-dash.svg`,
    },
    sidebarImg: `${COMPONENT_TYPES.ELECTRICAL}/floor-plan/wrap-light.svg`,
    desc: 'P602-1-01',
    objWidth: {
      TEN: 50,
      TWENTY: 170,
      FORTY: 375,
    },
    objHeight: 6,
    objType: COMPONENT_TYPES.ELECTRICAL,
    priceRecessed: 375,
    priceSurface: 450,
    model: '',
    fixed: true,
    ceilingOnly: true,
  },
].map((item) => ({ ...item, supplier: SUPPLIER_SLUGS.CUSTOM_CUBES }));

const atAndS = [
  {
    name: COMPONENT_NAMES.SKYLIGHT,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_SECURITY.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_SECURITY.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/window.svg`,
    desc: 'P201-1-01',
    objWidth: DIMENSIONS.WINDOW.WINDOW_SECURITY.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_SECURITY.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 1895,
    model: 'SM_Window 48x36_Hinged_Security_01',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/window.svg`,
  },
].map((item) => ({ ...item, supplier: SUPPLIER_SLUGS.AT_AND_S }));

export const electricalComponents = [...customCubes, ...atAndS];
