import { useGLTF } from '@react-three/drei';

const Interior = ({ supplier, selectedShedHeight, adjustForX, adjustForY, shedSize }) => {
  const { nodes, materials } = useGLTF(
    `/models/${supplier}/interiors/${selectedShedHeight}/${shedSize}/interiors.glb`
  );
  return (
    <group scale={8} dispose={null} position={[adjustForX, 0, adjustForY]}>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathroom_sink_porcelein001.geometry}
          material={materials['sink_porcelain.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathroom_ground.geometry}
          material={materials['bathroom_ground.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathroom_sink.geometry}
          material={materials['sink.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathroom_toilet.geometry}
          material={materials['toilet_porcelain.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathtub.geometry}
          material={materials.bathtub}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathtub_ceramics.geometry}
          material={materials['Tile reflective']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathtub_glass.geometry}
          material={materials['Gray Glass (7)']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bathtub_metal.geometry}
          material={materials.bathtub_metal_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mirrorcab_cabinet.geometry}
          material={materials['mirrorcab.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mirrorcab_mirror.geometry}
          material={materials['mirror.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sink_mixer.geometry}
          material={materials['sink_mixer.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.towel_handle.geometry}
          material={materials['towel_handle.001_2']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bed_grey.geometry}
          material={materials.bed_grey_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bed_white.geometry}
          material={materials.bed_white_2}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door1_frame.geometry}
          material={materials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door2_frame.geometry}
          material={materials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_metal.geometry}
          material={materials.door_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_metal001.geometry}
          material={materials.door_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doormetal.geometry}
          material={materials['PDM Grey metal Door_Handle_01']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.grey_door.geometry}
          material={materials.Material_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['wood-door1'].geometry}
          material={materials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['wood-door2'].geometry}
          material={materials['wood door']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kitchenette_black001.geometry}
          material={materials['kitchenette_black.001_2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kitchenette_metal001.geometry}
          material={materials['kitchenette_metal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kitchenette_mixer001.geometry}
          material={materials['kitchenette_mixer.001_2']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.kitchenette_white001.geometry}
          material={materials['kichenette_white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1.geometry}
          material={materials['kichenette_white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['kichenette_white.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.sink_porcelain}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.kitchenette_wood_oak}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.kitchenette_wood_oak}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.kitchenette_wood_oak}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Fencing_Mesh_Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Color_A06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['*1']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed_metal.geometry}
        material={materials['kitchenette_metal.002']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GF_interiorwall.geometry}
        material={materials.GF_interior}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1001.geometry}
        material={materials['metal_stove.001']}
        scale={0.025}
      />
    </group>
  );
};

export default Interior;
