import { useGLTF } from '@react-three/drei';

const Interior = ({ supplier, selectedShedHeight, adjustForX, adjustForY, shedSize }) => {
  const { nodes, materials } = useGLTF(
    `/models/${supplier}/interiors/${selectedShedHeight}/${shedSize}/interiors.glb`
  );
  return (
    <group scale={8} dispose={null} position={[adjustForX, 0, adjustForY]}>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GF_interiorwall1.geometry}
          material={materials['GF_interior.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GF_interiorwall2.geometry}
          material={materials['GF_interior.001']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['wood door']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2003.geometry}
          material={materials['toilet_porcelain.001']}
          position={[0, 0.379, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed_grey.geometry}
        material={materials.bed_grey}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed_metal.geometry}
        material={materials['kitchenette_metal.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bed_white.geometry}
        material={materials.bed_white}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchenette_black.geometry}
        material={materials['kitchenette_black.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchenette_white.geometry}
        material={materials['kichenette_white.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchenette_mixer.geometry}
        material={materials['kitchenette_mixer.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchenette_wood.geometry}
        material={materials['kitchenette_wood_oak.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.kitchenette_metal.geometry}
        material={materials['kitchenette_metal.002']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.door_metal}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Material_8}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials['PDM Grey metal Door_Handle_01']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2002.geometry}
        material={materials['Tile reflective']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3002.geometry}
        material={materials.bathtub}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bathtub_metal.geometry}
        material={materials.bathtub_metal}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bathtub_glass001.geometry}
        material={materials['Gray Glass (7)']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.towel_handle.geometry}
        material={materials['towel_handle.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1002.geometry}
        material={materials['sink_mixer.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2004.geometry}
        material={materials['sink_porcelain.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3003.geometry}
        material={materials['sink.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4001.geometry}
        material={materials['mirrorcab.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5001.geometry}
        material={materials['mirror.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bathroom_ground001.geometry}
        material={materials['bathroom_ground.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_1.geometry}
        material={materials['GF_interior.001']}
        scale={0.025}
      />
    </group>
  );
};

export default Interior;
