import { useGLTF } from '@react-three/drei';

const Interior = ({
  supplier,
  selectedShedHeight,
  adjustForX,
  adjustForY,
  shedSize,
  showSecondFloor,
}) => {
  const { nodes: gfNodes, materials: gfMaterials } = useGLTF(
    `/models/${supplier}/interiors/${selectedShedHeight}/${shedSize}/interiorGF.glb`
  );
  const { nodes: ffNodes, materials: ffMaterials } = useGLTF(
    `/models/${supplier}/interiors/${selectedShedHeight}/${shedSize}/interiorFF.glb`
  );

  const secondFloorMesh = (
    <>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bathroom_sink_porcelein_2.geometry}
          material={ffMaterials['sink_porcelain.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bathroom_sink.geometry}
          material={ffMaterials.sink}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bathroom_toilet.geometry}
          material={ffMaterials['toilet_porcelain.001 ']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.mirrorcab_cabinet.geometry}
          material={ffMaterials.mirrorcab}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.mirrorcab_mirror.geometry}
          material={ffMaterials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_1001.geometry}
          material={ffMaterials['bathroom_ground.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_2.geometry}
          material={ffMaterials.bathtub}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_3.geometry}
          material={ffMaterials['Tile reflective']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.sink_mixer.geometry}
          material={ffMaterials.sink_mixer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.towel_handle.geometry}
          material={ffMaterials.towel_handle}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_grey.geometry}
          material={ffMaterials.bed_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_grey_2.geometry}
          material={ffMaterials.bed_grey}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_metal.geometry}
          material={ffMaterials['kitchenette_metal.001 [imported].001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_metal_2.geometry}
          material={ffMaterials['kitchenette_metal.001 [imported].001']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_white.geometry}
          material={ffMaterials.bed_white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.bed_white_2.geometry}
          material={ffMaterials.bed_white}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_37.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_5.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_6.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_7.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_8.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_9.geometry}
          material={ffMaterials.FF_interior}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_10.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_11.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_12.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_13.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_14.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_15.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_16.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_17.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_18.geometry}
          material={ffMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_19.geometry}
          material={ffMaterials.Base_Board}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_20.geometry}
          material={ffMaterials['PDM Grey metal Door_Handle_01 [imported]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_24.geometry}
          material={ffMaterials['PDM Grey metal Door_Handle_01 [imported]']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_21.geometry}
          material={ffMaterials.door_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_23.geometry}
          material={ffMaterials.door_metal}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_25.geometry}
          material={ffMaterials.door_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_28.geometry}
          material={ffMaterials.door_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_31.geometry}
          material={ffMaterials.door_metal}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_26.geometry}
          material={ffMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_27.geometry}
          material={ffMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_29.geometry}
          material={ffMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_30.geometry}
          material={ffMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_32.geometry}
          material={ffMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_33.geometry}
          material={ffMaterials['wood door']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_34.geometry}
          material={ffMaterials.FF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={ffNodes.Object_35.geometry}
          material={ffMaterials.FF_interior}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh.geometry}
        material={ffMaterials['Material-Color_008_1']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh001.geometry}
        material={ffMaterials['Material-Color_006']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh002.geometry}
        material={ffMaterials['Material-Color_008']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh003.geometry}
        material={ffMaterials['Material-Color_001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh004.geometry}
        material={ffMaterials['Material-Color_002']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh005.geometry}
        material={ffMaterials['Material-257676512521']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh006.geometry}
        material={ffMaterials['Material-Color_005']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh007.geometry}
        material={ffMaterials['Material-75682435643564']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh008.geometry}
        material={ffMaterials['a0000000-0000-0000-0000-000000000000']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh009.geometry}
        material={ffMaterials['Material-75682435643564.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh010.geometry}
        material={ffMaterials['Material-Color_005.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh011.geometry}
        material={ffMaterials['Material-257676512521.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh012.geometry}
        material={ffMaterials['Material-Color_002.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh013.geometry}
        material={ffMaterials['Material-Color_001.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh014.geometry}
        material={ffMaterials['Material-Color_008.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh015.geometry}
        material={ffMaterials['Material-Color_006.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Mesh016.geometry}
        material={ffMaterials['a0000000-0000-0000-0000-000000000000']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Object_1.geometry}
        material={ffMaterials['bathtub_metal.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Object_4.geometry}
        material={ffMaterials['Gray Glass.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={ffNodes.Object_36.geometry}
        material={ffMaterials.stair_wood}
        scale={0.025}
      />
    </>
  );

  const firstFloorMesh = (
    <>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_10.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_11.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_12.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_13.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_14.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_17.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_18.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_19.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_2.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_20.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_24.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_25.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_26.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_27.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_28.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_29.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_3.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_30.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_31.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_32.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_33.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_34.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_37.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_38.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_4.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_41.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_43.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_44.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_46.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_47.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_49.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_5.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_50.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_51.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_52.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_53.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_54.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_55.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_56.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_57.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_58.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_59.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_60.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_61.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_64.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_65.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_66.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_67.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_69.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_70.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_71.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_72.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_73.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_74.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_75.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_77.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_78.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_79.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_8.geometry}
          material={gfMaterials.cabinets}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_9.geometry}
          material={gfMaterials.cabinets}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_15.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_16.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_21.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_22.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_23.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_35.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_39.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_40.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_42.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_45.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_48.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_6.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_62.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_63.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_68.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_7.geometry}
          material={gfMaterials.kitchenette_handle}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_76.geometry}
          material={gfMaterials.kitchenette_handle}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.bathroom_sink_porcelein_2.geometry}
          material={gfMaterials['sink_porcelain.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.bathroom_sink.geometry}
          material={gfMaterials.sink}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.bathroom_toilet.geometry}
          material={gfMaterials['toilet_porcelain.001 ']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.kitchenette_mixer001.geometry}
          material={gfMaterials.kitchenette_mixer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.mirrorcab_cabinet.geometry}
          material={gfMaterials.mirrorcab}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.mirrorcab_mirror.geometry}
          material={gfMaterials.mirror}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_1001.geometry}
          material={gfMaterials['bathroom_ground.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_36.geometry}
          material={gfMaterials.sink_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.sink_mixer.geometry}
          material={gfMaterials.sink_mixer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.towel_handle.geometry}
          material={gfMaterials.towel_handle}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_80.geometry}
          material={gfMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_81.geometry}
          material={gfMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_84.geometry}
          material={gfMaterials['wood door']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_85.geometry}
          material={gfMaterials['wood door']}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_82.geometry}
          material={gfMaterials.Material_83}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_86.geometry}
          material={gfMaterials.Material_83}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_109.geometry}
          material={gfMaterials.GF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_87.geometry}
          material={gfMaterials.GF_interior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_88.geometry}
          material={gfMaterials.GF_interior}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_89.geometry}
          material={gfMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_90.geometry}
          material={gfMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_91.geometry}
          material={gfMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_92.geometry}
          material={gfMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_93.geometry}
          material={gfMaterials.Base_Board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_94.geometry}
          material={gfMaterials.Base_Board}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_100.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_101.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_102.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_103.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_104.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_105.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_106.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_108.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_95.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_96.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_97.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_98.geometry}
          material={gfMaterials.Stair_Flooring}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_99.geometry}
          material={gfMaterials.Stair_Flooring}
        />
      </group>
      <group scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_1002.geometry}
          material={gfMaterials['*1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_2001.geometry}
          material={gfMaterials.Color_A06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_3001.geometry}
          material={gfMaterials['*1']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_4001.geometry}
          material={gfMaterials.Color_A06}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.Object_6001.geometry}
          material={gfMaterials['metal_stove.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.defaultMaterial.geometry}
        material={gfMaterials['Material-DefaultMaterial']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh.geometry}
        material={gfMaterials['Material-fridge_steel.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.defaultMaterial003.geometry}
        material={gfMaterials['Material-Oven__1_']}
        position={[-0.021, 0, 0]}
        scale={0.025}
      />
      <group position={[-0.021, 0, 0]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.defaultMaterial002_1.geometry}
          material={gfMaterials['Material-Oven_']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={gfNodes.defaultMaterial002_2.geometry}
          material={gfMaterials['Material.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.defaultMaterial001.geometry}
        material={gfMaterials['Material-Oven.003']}
        position={[-0.021, 0, 0]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.SM_Dishwasher_M_Dishwasher_0.geometry}
        material={gfMaterials['Material-M_Dishwasher']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Brep.geometry}
        material={gfMaterials['Material-dishwasher_matwhite']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh001.geometry}
        material={gfMaterials['Material-Color_008_1']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh002.geometry}
        material={gfMaterials['Material-Color_006']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh003.geometry}
        material={gfMaterials['Material-Color_008']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh004.geometry}
        material={gfMaterials['Material-Color_001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh005.geometry}
        material={gfMaterials['Material-Color_002']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh006.geometry}
        material={gfMaterials['Material-257676512521']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh007.geometry}
        material={gfMaterials['Material-Color_005']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh008.geometry}
        material={gfMaterials['Material-75682435643564']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh009.geometry}
        material={gfMaterials['a0000000-0000-0000-0000-000000000000']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh010.geometry}
        material={gfMaterials['Material-75682435643564.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh011.geometry}
        material={gfMaterials['Material-Color_005.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh012.geometry}
        material={gfMaterials['Material-257676512521.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh013.geometry}
        material={gfMaterials['Material-Color_002.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh014.geometry}
        material={gfMaterials['Material-Color_001.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh015.geometry}
        material={gfMaterials['Material-Color_008.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh016.geometry}
        material={gfMaterials['Material-Color_006.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Mesh017.geometry}
        material={gfMaterials['a0000000-0000-0000-0000-000000000000']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Object_1.geometry}
        material={gfMaterials['kitchenette_wood_oak.001']}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Object_107.geometry}
        material={gfMaterials.stair_wood}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Object_5001.geometry}
        material={gfMaterials.Fencing_Mesh_Blue}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={gfNodes.Object_7001.geometry}
        material={gfMaterials['sink_porcelain.004']}
        scale={0.025}
      />
    </>
  );

  return (
    <group scale={8} dispose={null} position={[adjustForX, 0, adjustForY]}>
      {showSecondFloor && secondFloorMesh}
      {firstFloorMesh}
    </group>
  );
};

export default Interior;
