import { DIMENSIONS } from '../../dimensions/dimensions';
import { COMPONENT_NAMES, COMPONENT_TYPES, SUPPLIER_SLUGS } from '../../names/names';

export const compactCottages = [
  {
    name: COMPONENT_NAMES.WINDOW_24_24,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_24_24.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_24_24.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/24x24.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/24x24.jpg`,
    desc: COMPONENT_NAMES.WINDOW_24_24,
    objWidth: DIMENSIONS.WINDOW.WINDOW_24_24.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_24_24.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_24_24.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '24x24',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/24x24.svg`,
  },
  {
    name: COMPONENT_NAMES.WINDOW_30_36,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_30_36.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_30_36.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/30x36.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/30x36.jpg`,
    desc: COMPONENT_NAMES.WINDOW_30_36,
    objWidth: DIMENSIONS.WINDOW.WINDOW_30_36.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_30_36.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_30_36.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '30x36',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/30x36.svg`,
  },
  {
    name: COMPONENT_NAMES.WINDOW_48_24,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_48_24.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_48_24.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/48x24.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/48x24.jpg`,
    desc: COMPONENT_NAMES.WINDOW_48_24,
    objWidth: DIMENSIONS.WINDOW.WINDOW_48_24.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_48_24.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_48_24.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '48x24',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/48x24.svg`,
  },
  {
    name: COMPONENT_NAMES.WINDOW_48_48,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_48_48.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_48_48.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/48x48.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/48x48.jpg`,
    desc: COMPONENT_NAMES.WINDOW_48_48,
    objWidth: DIMENSIONS.WINDOW.WINDOW_48_48.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_48_48.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_48_48.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '48x48',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/48x48.svg`,
  },
  {
    name: COMPONENT_NAMES.WINDOW_48_60,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_48_60.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_48_60.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/48x60.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/48x60.jpg`,
    desc: COMPONENT_NAMES.WINDOW_48_60,
    objWidth: DIMENSIONS.WINDOW.WINDOW_48_60.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_48_60.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_48_60.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '48x60',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/48x60.svg`,
  },
  {
    name: COMPONENT_NAMES.WINDOW_60_48,
    position: {
      x: DIMENSIONS.WINDOW.WINDOW_60_48.POSITION.x,
      y: DIMENSIONS.WINDOW.WINDOW_60_48.POSITION.y,
    },
    imgName: `${COMPONENT_TYPES.WINDOW}/front-view/60x48.svg`,
    sidebarImg: `${COMPONENT_TYPES.WINDOW}/sidebar/60x48.jpg`,
    desc: COMPONENT_NAMES.WINDOW_60_48,
    objWidth: DIMENSIONS.WINDOW.WINDOW_60_48.WIDTH,
    objHeight: DIMENSIONS.WINDOW.WINDOW_60_48.HEIGHT,
    objFpHeight: DIMENSIONS.WINDOW.WINDOW_60_48.FP_HEIGHT,
    objType: COMPONENT_TYPES.WINDOW,
    price: 0,
    model: '60x48',
    floorPlanImg: `${COMPONENT_TYPES.WINDOW}/floor-plan/60x48.svg`,
  },
].map(item => ({ ...item, supplier: SUPPLIER_SLUGS.COMPACT_COTTAGES }));
