import { AT_AND_S_WINDOW_DIMENSIONS } from "./atAndS";
import { COMPACT_COTTAGE_WINDOW_DIMENSIONS } from "./compactCottages";
import { CUSTOM_CUBE_WINDOW_DIMENSIONS } from "./customCubes";

export const WINDOW_DIMENSIONS = {
  ...CUSTOM_CUBE_WINDOW_DIMENSIONS,
  ...AT_AND_S_WINDOW_DIMENSIONS,
  ...COMPACT_COTTAGE_WINDOW_DIMENSIONS
}